// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdcX-htRZLOieCUERtGJ-ouVhTzG2TBY',
    appId: '1:192098989997:web:ab3d72f94314b2a5aa5324',
    messagingSenderId: '192098989997',
    projectId: 'fodo-70bc6',
    authDomain: 'fodo-70bc6.firebaseapp.com',
    databaseURL: 'https://fodo-70bc6-default-rtdb.firebaseio.com',
    storageBucket: 'fodo-70bc6.firebasestorage.app',
    measurementId: 'G-7EYQPKQK1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNCn9T4uS8eZadohsEkItpnEumFqvH-Q',
    appId: '1:192098989997:android:2d5c07c3ca484b61aa5324',
    messagingSenderId: '192098989997',
    projectId: 'fodo-70bc6',
    databaseURL: 'https://fodo-70bc6-default-rtdb.firebaseio.com',
    storageBucket: 'fodo-70bc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIn985wuoEfG0OmaJ46c3NbXU0UwvU86g',
    appId: '1:192098989997:ios:3383f249b83240a5aa5324',
    messagingSenderId: '192098989997',
    projectId: 'fodo-70bc6',
    databaseURL: 'https://fodo-70bc6-default-rtdb.firebaseio.com',
    storageBucket: 'fodo-70bc6.firebasestorage.app',
    iosBundleId: 'com.example.fodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIn985wuoEfG0OmaJ46c3NbXU0UwvU86g',
    appId: '1:192098989997:ios:3383f249b83240a5aa5324',
    messagingSenderId: '192098989997',
    projectId: 'fodo-70bc6',
    databaseURL: 'https://fodo-70bc6-default-rtdb.firebaseio.com',
    storageBucket: 'fodo-70bc6.firebasestorage.app',
    iosBundleId: 'com.example.fodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrdcX-htRZLOieCUERtGJ-ouVhTzG2TBY',
    appId: '1:192098989997:web:9c6edeb9acd22fc8aa5324',
    messagingSenderId: '192098989997',
    projectId: 'fodo-70bc6',
    authDomain: 'fodo-70bc6.firebaseapp.com',
    databaseURL: 'https://fodo-70bc6-default-rtdb.firebaseio.com',
    storageBucket: 'fodo-70bc6.firebasestorage.app',
    measurementId: 'G-XL1V48BPVC',
  );
}
